/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const CategoryType = IDL.Variant({
  'expense' : IDL.Null,
  'income' : IDL.Null,
});
export const Category = IDL.Record({
  'id' : IDL.Text,
  'categoryType' : CategoryType,
  'icon' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'color' : IDL.Text,
});
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'categoryId' : IDL.Text,
  'transactionType' : CategoryType,
  'date' : IDL.Int,
  'note' : IDL.Text,
  'receiptId' : IDL.Opt(IDL.Text),
  'amount' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CashflowInsights = IDL.Record({
  'averageMonthlyIncome' : IDL.Nat,
  'largestExpenseCategoryCurrentMonth' : IDL.Opt(IDL.Text),
  'healthIndicator' : IDL.Variant({
    'Safe' : IDL.Null,
    'Overspending' : IDL.Null,
    'Warning' : IDL.Null,
  }),
  'averageMonthlyExpense' : IDL.Nat,
  'monthOverMonthIncomeChange' : IDL.Int,
  'monthOverMonthExpenseChange' : IDL.Int,
  'endOfMonthBalanceForecast' : IDL.Int,
});
export const PaginatedCategories = IDL.Record({
  'total' : IDL.Nat,
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'items' : IDL.Vec(Category),
});
export const PaginatedTransactions = IDL.Record({
  'total' : IDL.Nat,
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'items' : IDL.Vec(Transaction),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCategory' : IDL.Func([Category], [], []),
  'addTransaction' : IDL.Func([Transaction], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCategory' : IDL.Func([IDL.Text], [], []),
  'deleteReceipt' : IDL.Func([IDL.Text], [], []),
  'deleteTransaction' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCashflowInsights' : IDL.Func([], [CashflowInsights], ['query']),
  'getCategories' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [PaginatedCategories],
      ['query'],
    ),
  'getCategoriesByType' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getCategoriesSortedByColor' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getCategory' : IDL.Func([IDL.Text], [IDL.Opt(Category)], ['query']),
  'getReceipt' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Vec(IDL.Nat8))], ['query']),
  'getTransaction' : IDL.Func([IDL.Text], [IDL.Opt(Transaction)], ['query']),
  'getTransactions' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [PaginatedTransactions],
      ['query'],
    ),
  'getTransactionsByCategory' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [PaginatedTransactions],
      ['query'],
    ),
  'getTransactionsByType' : IDL.Func(
      [CategoryType, IDL.Nat, IDL.Nat],
      [PaginatedTransactions],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchTransactions' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [PaginatedTransactions],
      ['query'],
    ),
  'updateCategory' : IDL.Func([Category], [], []),
  'updateTransaction' : IDL.Func([Transaction], [], []),
  'uploadReceipt' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat8)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const CategoryType = IDL.Variant({
    'expense' : IDL.Null,
    'income' : IDL.Null,
  });
  const Category = IDL.Record({
    'id' : IDL.Text,
    'categoryType' : CategoryType,
    'icon' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'color' : IDL.Text,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'categoryId' : IDL.Text,
    'transactionType' : CategoryType,
    'date' : IDL.Int,
    'note' : IDL.Text,
    'receiptId' : IDL.Opt(IDL.Text),
    'amount' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CashflowInsights = IDL.Record({
    'averageMonthlyIncome' : IDL.Nat,
    'largestExpenseCategoryCurrentMonth' : IDL.Opt(IDL.Text),
    'healthIndicator' : IDL.Variant({
      'Safe' : IDL.Null,
      'Overspending' : IDL.Null,
      'Warning' : IDL.Null,
    }),
    'averageMonthlyExpense' : IDL.Nat,
    'monthOverMonthIncomeChange' : IDL.Int,
    'monthOverMonthExpenseChange' : IDL.Int,
    'endOfMonthBalanceForecast' : IDL.Int,
  });
  const PaginatedCategories = IDL.Record({
    'total' : IDL.Nat,
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'items' : IDL.Vec(Category),
  });
  const PaginatedTransactions = IDL.Record({
    'total' : IDL.Nat,
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'items' : IDL.Vec(Transaction),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCategory' : IDL.Func([Category], [], []),
    'addTransaction' : IDL.Func([Transaction], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCategory' : IDL.Func([IDL.Text], [], []),
    'deleteReceipt' : IDL.Func([IDL.Text], [], []),
    'deleteTransaction' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCashflowInsights' : IDL.Func([], [CashflowInsights], ['query']),
    'getCategories' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [PaginatedCategories],
        ['query'],
      ),
    'getCategoriesByType' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getCategoriesSortedByColor' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getCategory' : IDL.Func([IDL.Text], [IDL.Opt(Category)], ['query']),
    'getReceipt' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    'getTransaction' : IDL.Func([IDL.Text], [IDL.Opt(Transaction)], ['query']),
    'getTransactions' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [PaginatedTransactions],
        ['query'],
      ),
    'getTransactionsByCategory' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [PaginatedTransactions],
        ['query'],
      ),
    'getTransactionsByType' : IDL.Func(
        [CategoryType, IDL.Nat, IDL.Nat],
        [PaginatedTransactions],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchTransactions' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [PaginatedTransactions],
        ['query'],
      ),
    'updateCategory' : IDL.Func([Category], [], []),
    'updateTransaction' : IDL.Func([Transaction], [], []),
    'uploadReceipt' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat8)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };