/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CashflowInsights {
  'averageMonthlyIncome' : bigint,
  'largestExpenseCategoryCurrentMonth' : [] | [string],
  'healthIndicator' : { 'Safe' : null } |
    { 'Overspending' : null } |
    { 'Warning' : null },
  'averageMonthlyExpense' : bigint,
  'monthOverMonthIncomeChange' : bigint,
  'monthOverMonthExpenseChange' : bigint,
  'endOfMonthBalanceForecast' : bigint,
}
export interface Category {
  'id' : string,
  'categoryType' : CategoryType,
  'icon' : [] | [string],
  'name' : string,
  'color' : string,
}
export type CategoryType = { 'expense' : null } |
  { 'income' : null };
export interface PaginatedCategories {
  'total' : bigint,
  'page' : bigint,
  'pageSize' : bigint,
  'items' : Array<Category>,
}
export interface PaginatedTransactions {
  'total' : bigint,
  'page' : bigint,
  'pageSize' : bigint,
  'items' : Array<Transaction>,
}
export interface Transaction {
  'id' : string,
  'categoryId' : string,
  'transactionType' : CategoryType,
  'date' : bigint,
  'note' : string,
  'receiptId' : [] | [string],
  'amount' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCategory' : ActorMethod<[Category], undefined>,
  'addTransaction' : ActorMethod<[Transaction], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCategory' : ActorMethod<[string], undefined>,
  'deleteReceipt' : ActorMethod<[string], undefined>,
  'deleteTransaction' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCashflowInsights' : ActorMethod<[], CashflowInsights>,
  'getCategories' : ActorMethod<[bigint, bigint], PaginatedCategories>,
  'getCategoriesByType' : ActorMethod<[], Array<Category>>,
  'getCategoriesSortedByColor' : ActorMethod<[], Array<Category>>,
  'getCategory' : ActorMethod<[string], [] | [Category]>,
  'getReceipt' : ActorMethod<[string], [] | [Uint8Array]>,
  'getTransaction' : ActorMethod<[string], [] | [Transaction]>,
  'getTransactions' : ActorMethod<[bigint, bigint], PaginatedTransactions>,
  'getTransactionsByCategory' : ActorMethod<
    [string, bigint, bigint],
    PaginatedTransactions
  >,
  'getTransactionsByType' : ActorMethod<
    [CategoryType, bigint, bigint],
    PaginatedTransactions
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchTransactions' : ActorMethod<
    [string, bigint, bigint],
    PaginatedTransactions
  >,
  'updateCategory' : ActorMethod<[Category], undefined>,
  'updateTransaction' : ActorMethod<[Transaction], undefined>,
  'uploadReceipt' : ActorMethod<[string, Uint8Array], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];