/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PaginatedTransactions {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    items: Array<Transaction>;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Category {
    id: string;
    categoryType: CategoryType;
    icon?: string;
    name: string;
    color: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface PaginatedCategories {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    items: Array<Category>;
}
export interface CashflowInsights {
    averageMonthlyIncome: bigint;
    largestExpenseCategoryCurrentMonth?: string;
    healthIndicator: Variant_Safe_Overspending_Warning;
    averageMonthlyExpense: bigint;
    monthOverMonthIncomeChange: bigint;
    monthOverMonthExpenseChange: bigint;
    endOfMonthBalanceForecast: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface UserProfile {
    name: string;
}
export interface Transaction {
    id: string;
    categoryId: string;
    transactionType: CategoryType;
    date: bigint;
    note: string;
    receiptId?: string;
    amount: bigint;
}
export enum CategoryType {
    expense = "expense",
    income = "income"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_Safe_Overspending_Warning {
    Safe = "Safe",
    Overspending = "Overspending",
    Warning = "Warning"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCategory(category: Category): Promise<void>;
    addTransaction(transaction: Transaction): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteCategory(categoryId: string): Promise<void>;
    deleteReceipt(receiptId: string): Promise<void>;
    deleteTransaction(transactionId: string): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCashflowInsights(): Promise<CashflowInsights>;
    getCategories(page: bigint, pageSize: bigint): Promise<PaginatedCategories>;
    getCategoriesByType(): Promise<Array<Category>>;
    getCategoriesSortedByColor(): Promise<Array<Category>>;
    getCategory(categoryId: string): Promise<Category | null>;
    getReceipt(receiptId: string): Promise<Uint8Array | null>;
    getTransaction(transactionId: string): Promise<Transaction | null>;
    getTransactions(page: bigint, pageSize: bigint): Promise<PaginatedTransactions>;
    getTransactionsByCategory(categoryId: string, page: bigint, pageSize: bigint): Promise<PaginatedTransactions>;
    getTransactionsByType(transactionType: CategoryType, page: bigint, pageSize: bigint): Promise<PaginatedTransactions>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchTransactions(searchTerm: string, page: bigint, pageSize: bigint): Promise<PaginatedTransactions>;
    updateCategory(category: Category): Promise<void>;
    updateTransaction(transaction: Transaction): Promise<void>;
    uploadReceipt(receiptId: string, imageData: Uint8Array): Promise<void>;
}
import type { CashflowInsights as _CashflowInsights, Category as _Category, CategoryType as _CategoryType, PaginatedCategories as _PaginatedCategories, PaginatedTransactions as _PaginatedTransactions, Transaction as _Transaction, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCategory(arg0: Category): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCategory(to_candid_Category_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCategory(to_candid_Category_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addTransaction(arg0: Transaction): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(to_candid_Transaction_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(to_candid_Transaction_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteCategory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCategory(arg0);
            return result;
        }
    }
    async deleteReceipt(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReceipt(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReceipt(arg0);
            return result;
        }
    }
    async deleteTransaction(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTransaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTransaction(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCashflowInsights(): Promise<CashflowInsights> {
        if (this.processError) {
            try {
                const result = await this.actor.getCashflowInsights();
                return from_candid_CashflowInsights_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCashflowInsights();
            return from_candid_CashflowInsights_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategories(arg0: bigint, arg1: bigint): Promise<PaginatedCategories> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategories(arg0, arg1);
                return from_candid_PaginatedCategories_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategories(arg0, arg1);
            return from_candid_PaginatedCategories_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategoriesByType(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategoriesByType();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategoriesByType();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategoriesSortedByColor(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategoriesSortedByColor();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategoriesSortedByColor();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategory(arg0: string): Promise<Category | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategory(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategory(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReceipt(arg0: string): Promise<Uint8Array | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReceipt(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReceipt(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransaction(arg0: string): Promise<Transaction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransaction(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransaction(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactions(arg0: bigint, arg1: bigint): Promise<PaginatedTransactions> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactions(arg0, arg1);
                return from_candid_PaginatedTransactions_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactions(arg0, arg1);
            return from_candid_PaginatedTransactions_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionsByCategory(arg0: string, arg1: bigint, arg2: bigint): Promise<PaginatedTransactions> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionsByCategory(arg0, arg1, arg2);
                return from_candid_PaginatedTransactions_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionsByCategory(arg0, arg1, arg2);
            return from_candid_PaginatedTransactions_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionsByType(arg0: CategoryType, arg1: bigint, arg2: bigint): Promise<PaginatedTransactions> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionsByType(to_candid_CategoryType_n10(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_PaginatedTransactions_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionsByType(to_candid_CategoryType_n10(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_PaginatedTransactions_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchTransactions(arg0: string, arg1: bigint, arg2: bigint): Promise<PaginatedTransactions> {
        if (this.processError) {
            try {
                const result = await this.actor.searchTransactions(arg0, arg1, arg2);
                return from_candid_PaginatedTransactions_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchTransactions(arg0, arg1, arg2);
            return from_candid_PaginatedTransactions_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCategory(arg0: Category): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCategory(to_candid_Category_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCategory(to_candid_Category_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateTransaction(arg0: Transaction): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTransaction(to_candid_Transaction_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTransaction(to_candid_Transaction_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async uploadReceipt(arg0: string, arg1: Uint8Array): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadReceipt(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadReceipt(arg0, arg1);
            return result;
        }
    }
}
function from_candid_CashflowInsights_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CashflowInsights): CashflowInsights {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_CategoryType_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CategoryType): CategoryType {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_PaginatedCategories_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaginatedCategories): PaginatedCategories {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_PaginatedTransactions_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaginatedTransactions): PaginatedTransactions {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Category]): Category | null {
    return value.length === 0 ? null : from_candid_Category_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Transaction]): Transaction | null {
    return value.length === 0 ? null : from_candid_Transaction_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    averageMonthlyIncome: bigint;
    largestExpenseCategoryCurrentMonth: [] | [string];
    healthIndicator: {
        Safe: null;
    } | {
        Overspending: null;
    } | {
        Warning: null;
    };
    averageMonthlyExpense: bigint;
    monthOverMonthIncomeChange: bigint;
    monthOverMonthExpenseChange: bigint;
    endOfMonthBalanceForecast: bigint;
}): {
    averageMonthlyIncome: bigint;
    largestExpenseCategoryCurrentMonth?: string;
    healthIndicator: Variant_Safe_Overspending_Warning;
    averageMonthlyExpense: bigint;
    monthOverMonthIncomeChange: bigint;
    monthOverMonthExpenseChange: bigint;
    endOfMonthBalanceForecast: bigint;
} {
    return {
        averageMonthlyIncome: value.averageMonthlyIncome,
        largestExpenseCategoryCurrentMonth: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.largestExpenseCategoryCurrentMonth)),
        healthIndicator: from_candid_variant_n22(_uploadFile, _downloadFile, value.healthIndicator),
        averageMonthlyExpense: value.averageMonthlyExpense,
        monthOverMonthIncomeChange: value.monthOverMonthIncomeChange,
        monthOverMonthExpenseChange: value.monthOverMonthExpenseChange,
        endOfMonthBalanceForecast: value.endOfMonthBalanceForecast
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    items: Array<_Category>;
}): {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    items: Array<Category>;
} {
    return {
        total: value.total,
        page: value.page,
        pageSize: value.pageSize,
        items: from_candid_vec_n25(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    categoryType: _CategoryType;
    icon: [] | [string];
    name: string;
    color: string;
}): {
    id: string;
    categoryType: CategoryType;
    icon?: string;
    name: string;
    color: string;
} {
    return {
        id: value.id,
        categoryType: from_candid_CategoryType_n28(_uploadFile, _downloadFile, value.categoryType),
        icon: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.icon)),
        name: value.name,
        color: value.color
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    categoryId: string;
    transactionType: _CategoryType;
    date: bigint;
    note: string;
    receiptId: [] | [string];
    amount: bigint;
}): {
    id: string;
    categoryId: string;
    transactionType: CategoryType;
    date: bigint;
    note: string;
    receiptId?: string;
    amount: bigint;
} {
    return {
        id: value.id,
        categoryId: value.categoryId,
        transactionType: from_candid_CategoryType_n28(_uploadFile, _downloadFile, value.transactionType),
        date: value.date,
        note: value.note,
        receiptId: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.receiptId)),
        amount: value.amount
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    items: Array<_Transaction>;
}): {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    items: Array<Transaction>;
} {
    return {
        total: value.total,
        page: value.page,
        pageSize: value.pageSize,
        items: from_candid_vec_n37(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Safe: null;
} | {
    Overspending: null;
} | {
    Warning: null;
}): Variant_Safe_Overspending_Warning {
    return "Safe" in value ? Variant_Safe_Overspending_Warning.Safe : "Overspending" in value ? Variant_Safe_Overspending_Warning.Overspending : "Warning" in value ? Variant_Safe_Overspending_Warning.Warning : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expense: null;
} | {
    income: null;
}): CategoryType {
    return "expense" in value ? CategoryType.expense : "income" in value ? CategoryType.income : value;
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Category>): Array<Category> {
    return value.map((x)=>from_candid_Category_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n33(_uploadFile, _downloadFile, x));
}
function to_candid_CategoryType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CategoryType): _CategoryType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Category_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_Transaction_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Transaction): _Transaction {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    categoryId: string;
    transactionType: CategoryType;
    date: bigint;
    note: string;
    receiptId?: string;
    amount: bigint;
}): {
    id: string;
    categoryId: string;
    transactionType: _CategoryType;
    date: bigint;
    note: string;
    receiptId: [] | [string];
    amount: bigint;
} {
    return {
        id: value.id,
        categoryId: value.categoryId,
        transactionType: to_candid_CategoryType_n10(_uploadFile, _downloadFile, value.transactionType),
        date: value.date,
        note: value.note,
        receiptId: value.receiptId ? candid_some(value.receiptId) : candid_none(),
        amount: value.amount
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    categoryType: CategoryType;
    icon?: string;
    name: string;
    color: string;
}): {
    id: string;
    categoryType: _CategoryType;
    icon: [] | [string];
    name: string;
    color: string;
} {
    return {
        id: value.id,
        categoryType: to_candid_CategoryType_n10(_uploadFile, _downloadFile, value.categoryType),
        icon: value.icon ? candid_some(value.icon) : candid_none(),
        name: value.name,
        color: value.color
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CategoryType): {
    expense: null;
} | {
    income: null;
} {
    return value == CategoryType.expense ? {
        expense: null
    } : value == CategoryType.income ? {
        income: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
